/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACES_GUI;

/**
 *
 * @author gta6b
 */
public class Claves extends javax.swing.JFrame {

    /**
     * Creates new form Claves
     */
    
    private String txt;
    public Claves() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Button512 = new javax.swing.JButton();
        Button1024 = new javax.swing.JButton();
        Button2056 = new javax.swing.JButton();
        Button3072 = new javax.swing.JButton();
        Button4096 = new javax.swing.JButton();
        Button8192 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("MS PGothic", 3, 18)); // NOI18N
        jLabel1.setText("SELECCIONA EL TAMAÑO DE LA CLAVE QUE DESEAS UTILIZAR PARA CIFRAR Y DESCIFRAR");

        Button512.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button512.setText("512 BITS");
        Button512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button512ActionPerformed(evt);
            }
        });

        Button1024.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button1024.setText("1024 BITS");
        Button1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1024ActionPerformed(evt);
            }
        });

        Button2056.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button2056.setText("2056 BITS");
        Button2056.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2056ActionPerformed(evt);
            }
        });

        Button3072.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button3072.setText("3072 BITS");
        Button3072.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3072ActionPerformed(evt);
            }
        });

        Button4096.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button4096.setText("4096 BITS");
        Button4096.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4096ActionPerformed(evt);
            }
        });

        Button8192.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Button8192.setText("8192 BITS");
        Button8192.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8192ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Recordemos que el tamaño de la clave es crítico para la seguridad del sistema, ya que un tamaño de clave más largo generalmente proporciona mayor seguridad, pero también implica operaciones más lentas.\nAquí hay una breve descripción de lo que generalmente se espera para diferentes tamaños de clave RSA:\n512 bits: Este tamaño de clave se considera inseguro para la mayoría de los propósitos en la actualidad debido a avances en la capacidad de cómputo. No se recomienda para aplicaciones de seguridad.\n1024 bits: También se considera inseguro para uso general debido a avances en la capacidad de cómputo. Aunque ha sido común en el pasado, se recomienda pasar a tamaños de clave más grandes para una mayor seguridad.\n2048 bits: Este es el tamaño de clave mínimo recomendado para uso general en la actualidad. Proporciona un buen equilibrio entre seguridad y rendimiento para muchas aplicaciones.\n3072 bits y superiores: Se consideran tamaños de clave más seguros y son recomendados para aplicaciones que requieren un nivel más alto de seguridad. Tamaños de clave como 4096 y 8192 bits son utilizados en situaciones donde se necesita una seguridad excepcionalmente fuerte.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button512)
                                .addGap(143, 143, 143)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button4096)
                                    .addComponent(Button1024)))
                            .addComponent(Button3072))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button2056)
                            .addComponent(Button8192)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button512)
                    .addComponent(Button2056)
                    .addComponent(Button1024))
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button3072)
                    .addComponent(Button4096)
                    .addComponent(Button8192))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button512ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(512, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Button512ActionPerformed

    private void Button1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1024ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(1024, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button1024ActionPerformed

    private void Button2056ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2056ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(2056, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button2056ActionPerformed

    private void Button3072ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3072ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(3072, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button3072ActionPerformed

    private void Button4096ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4096ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(4096, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button4096ActionPerformed

    private void Button8192ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8192ActionPerformed
        Cifrado res = new Cifrado();
        res.setLLave(8192, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Button8192ActionPerformed

    public void setTexto(String txt){
        this.txt = txt;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Claves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1024;
    private javax.swing.JButton Button2056;
    private javax.swing.JButton Button3072;
    private javax.swing.JButton Button4096;
    private javax.swing.JButton Button512;
    private javax.swing.JButton Button8192;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
